# Generated by Django 5.0.3 on 2024-08-30 12:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Album', '0001_initial'),
        ('Artist', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='album',
            name='ArtistId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Artist.artist'),
        ),
    ]
