# Generated by Django 5.1 on 2024-09-01 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Album', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='ReleaseDate',
            field=models.DateTimeField(help_text='Format: YYYY-MM-DDThh:mm[:ss[.uuuuuu]][+HH:MM|-HH:MM|Z]'),
        ),
    ]
