# Generated by Django 5.1 on 2024-09-01 23:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Album', '0004_alter_album_releasedate'),
        ('Genrer', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='album',
            name='gender',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Genrer.genrer'),
        ),
    ]
