# Generated by Django 5.1 on 2024-09-01 23:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Album', '0005_album_gender'),
        ('Genrer', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='album',
            name='gender',
        ),
        migrations.AddField(
            model_name='album',
            name='genres',
            field=models.ManyToManyField(blank=True, to='Genrer.genrer'),
        ),
    ]
