# Generated by Django 5.1 on 2024-09-03 22:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Album', '0008_rename_artistid_album_artist_alter_album_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='album',
            name='bio',
            field=models.TextField(blank=True, null=True),
        ),
    ]
