# Generated by Django 5.0.3 on 2024-09-09 13:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Album', '0011_alter_album_slug'),
        ('Artist', '0004_artist_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='Artist',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='albums', to='Artist.artist'),
        ),
    ]
