# Generated by Django 5.0.3 on 2024-09-04 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Artist', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='artist',
            name='age',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
