# Generated by Django 5.1 on 2024-09-01 23:07

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Track', '0002_alter_track_album'),
    ]

    operations = [
        migrations.AddField(
            model_name='track',
            name='music_file',
            field=models.FileField(blank=True, null=True, upload_to='music/'),
        ),
        migrations.AddField(
            model_name='track',
            name='uploaded_at',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
